### ISSUE TITLE
(optionally) show EXIF data about the photo when uploading compressed version

### ISSUE THREAD

**Issue by mralext20** [TopBakuhatsu/hitagibot#19]
example: uploaded photo has meta data related to focal length, or camera model. 
![screenshot from 2016-08-04 20-47-11](https://cloud.githubusercontent.com/assets/4016295/17426488/bdbda4dc-5a84-11e6-91fd-0348ba5e14c4.png)

**Comment by TopBakuhatsu** [comment]
I will implement in the next commit
